/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.domotics.proto.server;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface DomServer {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"DomServer\",\"namespace\":\"avro.domotics.proto.server\",\"types\":[],\"messages\":{\"ConnectUser\":{\"request\":[{\"name\":\"username\",\"type\":\"string\"}],\"response\":\"int\"},\"ConnectLight\":{\"request\":[{\"name\":\"LightID\",\"type\":\"int\"}],\"response\":\"int\"},\"ConnectFridge\":{\"request\":[{\"name\":\"FridgeID\",\"type\":\"int\"}],\"response\":\"int\"},\"Switch\":{\"request\":[{\"name\":\"lightID\",\"type\":\"int\"}],\"response\":\"boolean\"},\"GetClients\":{\"request\":[],\"response\":{\"type\":\"map\",\"values\":{\"type\":\"array\",\"items\":\"int\"}}},\"GetLights\":{\"request\":[],\"response\":{\"type\":\"map\",\"values\":\"boolean\"}},\"LeaveHouse\":{\"request\":[{\"name\":\"username\",\"type\":\"string\"}],\"response\":\"null\"},\"GetFridges\":{\"request\":[],\"response\":{\"type\":\"array\",\"items\":\"int\"}},\"ConnectUserToFridge\":{\"request\":[{\"name\":\"username\",\"type\":\"int\"},{\"name\":\"fridgeID\",\"type\":\"int\"}],\"response\":\"null\"},\"FridgeIsEmpty\":{\"request\":[{\"name\":\"fridgeID\",\"type\":\"int\"}],\"response\":\"null\"},\"IsAlive\":{\"request\":[],\"response\":\"boolean\"}}}");
  int ConnectUser(java.lang.CharSequence username) throws org.apache.avro.AvroRemoteException;
  int ConnectLight(int LightID) throws org.apache.avro.AvroRemoteException;
  int ConnectFridge(int FridgeID) throws org.apache.avro.AvroRemoteException;
  boolean Switch(int lightID) throws org.apache.avro.AvroRemoteException;
  java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Integer>> GetClients() throws org.apache.avro.AvroRemoteException;
  java.util.Map<java.lang.CharSequence,java.lang.Boolean> GetLights() throws org.apache.avro.AvroRemoteException;
  java.lang.Void LeaveHouse(java.lang.CharSequence username) throws org.apache.avro.AvroRemoteException;
  java.util.List<java.lang.Integer> GetFridges() throws org.apache.avro.AvroRemoteException;
  java.lang.Void ConnectUserToFridge(int username, int fridgeID) throws org.apache.avro.AvroRemoteException;
  java.lang.Void FridgeIsEmpty(int fridgeID) throws org.apache.avro.AvroRemoteException;
  boolean IsAlive() throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends DomServer {
    public static final org.apache.avro.Protocol PROTOCOL = avro.domotics.proto.server.DomServer.PROTOCOL;
    void ConnectUser(java.lang.CharSequence username, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    void ConnectLight(int LightID, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    void ConnectFridge(int FridgeID, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
    void Switch(int lightID, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    void GetClients(org.apache.avro.ipc.Callback<java.util.Map<java.lang.CharSequence,java.util.List<java.lang.Integer>>> callback) throws java.io.IOException;
    void GetLights(org.apache.avro.ipc.Callback<java.util.Map<java.lang.CharSequence,java.lang.Boolean>> callback) throws java.io.IOException;
    void LeaveHouse(java.lang.CharSequence username, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void GetFridges(org.apache.avro.ipc.Callback<java.util.List<java.lang.Integer>> callback) throws java.io.IOException;
    void ConnectUserToFridge(int username, int fridgeID, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void FridgeIsEmpty(int fridgeID, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void IsAlive(org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
  }
}