/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.domotics.proto.thermostat;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface thermostat {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"thermostat\",\"namespace\":\"avro.domotics.proto.thermostat\",\"types\":[],\"messages\":{\"GetTemperature\":{\"request\":[],\"response\":\"double\"},\"IsAlive\":{\"request\":[{\"name\":\"IPaddr\",\"type\":\"string\"},{\"name\":\"ID\",\"type\":\"int\"}],\"response\":\"boolean\"}}}");
  double GetTemperature() throws org.apache.avro.AvroRemoteException;
  boolean IsAlive(java.lang.CharSequence IPaddr, int ID) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends thermostat {
    public static final org.apache.avro.Protocol PROTOCOL = avro.domotics.proto.thermostat.thermostat.PROTOCOL;
    void GetTemperature(org.apache.avro.ipc.Callback<java.lang.Double> callback) throws java.io.IOException;
    void IsAlive(java.lang.CharSequence IPaddr, int ID, org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
  }
}