/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.domotics.proto.lights;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface Lights {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"Lights\",\"namespace\":\"avro.domotics.proto.lights\",\"types\":[],\"messages\":{\"LightSwitch\":{\"request\":[],\"response\":\"null\"},\"GetLightState\":{\"request\":[],\"response\":\"boolean\"},\"IsAlive\":{\"request\":[],\"response\":\"boolean\"}}}");
  java.lang.Void LightSwitch() throws org.apache.avro.AvroRemoteException;
  boolean GetLightState() throws org.apache.avro.AvroRemoteException;
  boolean IsAlive() throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends Lights {
    public static final org.apache.avro.Protocol PROTOCOL = avro.domotics.proto.lights.Lights.PROTOCOL;
    void LightSwitch(org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
    void GetLightState(org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
    void IsAlive(org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
  }
}