/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package avro.domotics.proto.user;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface User {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"User\",\"namespace\":\"avro.domotics.proto.user\",\"types\":[],\"messages\":{\"IsAlive\":{\"request\":[],\"response\":\"boolean\"}}}");
  boolean IsAlive() throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends User {
    public static final org.apache.avro.Protocol PROTOCOL = avro.domotics.proto.user.User.PROTOCOL;
    void IsAlive(org.apache.avro.ipc.Callback<java.lang.Boolean> callback) throws java.io.IOException;
  }
}